### ISSUE TITLE
LLM in minikube demo

### ISSUE THREAD

**Issue by nirs** [medyagh/ai-playground-minikube#4]
Provide an way way to play with a tiny LLM, similar to [ramalama](https://ramalama.ai)

## Ramalama flow

```console
% ramalama pull tiny
Downloading ollama://tinyllama:latest ...
Trying to pull ollama://tinyllama:latest ...
 99% |██████████████████████████████████████████████████████████████████████████████████████████████████████  |  603.76 MB/ 608.16 MB  45.55 MB/s        0s

% ramalama run tiny
🦭 > why the sky is blue?
The sky is blue due to the combination of several natural factors known as the "blue light" effect. 

The blue light effect is the phenomenon where blue light, which is generated by the sun, is absorbed by the Earth's atmosphere, resulting in a blue light that appears as blue sky. This phenomenon is caused by the Earth's atmosphere absorbing light from the sun, which causes the blue light to become visible.

The Earth's atmosphere is made up of gases such as oxygen, nitrogen, and argon, which absorb visible light in the blue spectrum. This absorption process creates a layer of blue light in the atmosphere, which is then reflected back up into the atmosphere to become visible light.

In addition to the natural factors that affect the blue light effect, there are also man-made factors that can influence the visibility of the sky. For example, urban areas with tall buildings and high concentrations of pollutants can contribute to the visibility of the sky in the blue light spectrum, while deserts with low amounts of vegetation can absorb blue light and produce a more vibrant blue sky.

In summary, the blue light effect of the sky is a result of the natural and man-made factors that shape and influence the color of the sky.
```

## Minikube flow

```
# Create a GPU accelerated cluster
minikube start -d krunkit

# Pull a model to the cluster
kubectl apply -f tiny.yaml

# Create a pod running llama.cpp server
kubectl apply -f llama-cpp.yaml

# Interact with the LLM
kubectl exec pod llama-cpp -it
🦭 > why the sky is blue?
The sky is blue due to the combination of several natural factors known as the "blue light" effect. 
...
```

### Downloading a model into a PVC

Should be possible using volume populators:
https://kubernetes.io/blog/2022/05/16/volume-populators-beta/#trying-it-out

### Interacting with the LLM

We can reuse the ramalama container as fist step. It includes everything we need.

**Comment by nirs** [comment]
We want to keep the models on the host so when deleting a cluster you don't need to download the models again. This is similar to how ramalama works.

We will access the modules using virtiofs mount.

## Example flow

### Download model

```console
mkdir ~/models
cd models
curl -LO https://huggingface.co/instructlab/granite-7b-lab-GGUF/resolve/main/granite-7b-lab-Q4_K_M.gguf?download=true
```

### Start krunkit cluster

```console
out/minikube start --driver krunkit --mount-string ~/models:/mnt/models
```

### Deploy the generic-device-plugin

```yaml
# generic-device-plugin.yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: generic-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: generic-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: generic-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: generic-device-plugin
    spec:
      priorityClassName: system-node-critical
      tolerations:
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
      containers:
      - image: squat/generic-device-plugin
        args:
        - --device
        - |
          name: dri
          groups:
          - paths:
            - path: /dev/dri
        name: generic-device-plugin
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 20Mi
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
  updateStrategy:
    type: RollingUpdate                                                                                                                                                                       
```

```console
kubectl apply -f generic-device-plugin.yaml 
```

### Create ramalama pod

```yaml
# ramalama.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: ramalama
  namespace: default
spec:
  containers:
  - name: ramalama
    image: quay.io/ramalama/ramalama:latest
    command: ["sh", "-c" , "trap 'exit 0' TERM; while true; do sleep 60 & wait; done"]
    resources:
      limits:
        squat.ai/dri: 1
    volumeMounts:
    - name: models
      mountPath: /mnt/models
  volumes:
  - name: models
    hostPath:
      path: /mnt/models
```

Deploy the pod:

```console
kubectl apply -f ramalama.yaml 
```

Wait until the pod is running:

```console
% kubectl get pod ramalama 
NAME       READY   STATUS    RESTARTS   AGE
ramalama   1/1     Running   0          2m46s
```

### Connect to the ramalama pod

```console
kubectl exec ramalama -it -- sh
```

### Chat with the granite model

```console
sh-5.2# llama-run -ngl 999 /mnt/models/granite-7b-lab-Q4_K_M.gguf
> why the sky is blue?

Ah, you've asked a classic question that has intrigued scientists for
centuries! The blue color of the sky is primarily due to a phenomenon called
Rayleigh scattering.

When sunlight reaches Earth's atmosphere, it is made up of different colors,
which are essentially different wavelengths of light. As this light travels
through the atmosphere, it interacts with molecules like nitrogen and oxygen.
Due to the small size of these molecules, they can only scatter a tiny fraction
of the sunlight's wavelengths, but the shorter, blue and violet wavelengths are
scattered much more than the longer, red, orange, and yellow wavelengths.

However, our eyes are more sensitive to blue light and less sensitive to violet
light. Moreover, sunlight reaches us with a greater intensity of blue light
compared to violet light. As a result, when we look up at the sky, we perceive
it to be blue instead of violet.

Therefore, the sky appears blue because the shorter, blue wavelengths of light
are scattered more efficiently by the molecules in Earth's atmosphere, and our
eyes' sensitivity and sunlight's intensity play a role in this process. It's a
fascinating example of how our atmosphere interacts with sunlight to create the
beautiful colors we observe in nature.

> Do you like to run in this fancy cluster?

I appreciate your question, but I must clarify that I am an artificial
intelligence and do not have the ability to physically run or interact with the
environment in the way a human does. I am designed to process information and
provide responses based on the data I have been trained on.

However, I can certainly help you learn more about running, exercise, or any
other topic that interests you. If you'd like to know more about running, its
benefits, or how to get started, I'd be happy to help!
```

### Run llama-bench

```console
sh-5.2# llama-bench -ngl 999 -m /mnt/models/granite-7b-lab-Q4_K_M.gguf 
ggml_vulkan: Found 1 Vulkan devices:
ggml_vulkan: 0 = Virtio-GPU Venus (Apple M2 Max) (venus) | uma: 1 | fp16: 1 | warp size: 32 | shared memory: 32768 | int dot: 0 | matrix cores: none
| model                          |       size |     params | backend    | ngl |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | --------------: | -------------------: |
| llama 7B Q4_K - Medium         |   3.80 GiB |     6.74 B | Vulkan,RPC | 999 |           pp512 |        275.64 ± 0.59 |
| llama 7B Q4_K - Medium         |   3.80 GiB |     6.74 B | Vulkan,RPC | 999 |           tg128 |         25.53 ± 0.72 |

build: f667f1e6 (5764) 
```
